### ISSUE TITLE
checklist: jobs before the day

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#131]
Taken from https://github.com/clojurebridge-berlin/organization/wiki/Checklist:-Jobs-on-the-Day-%E2%9C%85

## some time before the workshop
* [x] get the key to the fuse box 
* [x]  get the hausmeister's number 
* [x]  get some spare key cards 
* [ ]  extra verlaengerungskabel + chargers?
* [x]  prepare badges: visualize role on the badge: coach, attendee, volunteer
* [ ]  decide on quiet room - make sure it's easily/discreetly accessible
* [ ]  print list of venue emergency contacts
* [x]  print sign for quiet room saying Quiet room | Ruhe Raum 
* [x]  print sign for toilets incl. all gender bathroom sign
* [ ]  print check-in lists for coaches/attendees
* [ ]  prepare a list of who is inside the building for emergency (may be a column in the above)
* [x]  print code of conduct (in EN and DE)
* [x]  print guest policy
* [x]  print out responding to CoC guidelines 
* [x]  print out (...and write) a form for project group sign up

**Comment by vsmart** [comment]
🎉
