### ISSUE TITLE
Speakers

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#152]
We will plan lightning talks with motivational speakers. 

Some previous discussion for reference:
* https://github.com/clojurebridge-berlin/organization/issues/95
* https://github.com/clojurebridge-berlin/organization/issues/83
* https://github.com/clojurebridge-berlin/organization/issues/51

## Todo: 

* [x] brainstorm interesting people, preferably nb people + women, to speak on tech, clojure, code, or related
* [x] get in touch with them
* [x] get speaker confirmation including CoC signoff (we have a google form for this -- @vsmart to put up later)
* [x] put confirmed speakers on the list below 

## Confirmed Speakers 

* Catherine - Switching to Tech from Academia (EN)
* Camilla - 3 annoying things about programming (EN)
* Igor - The power of 2 (EN)
* Marie - Mitmischen (DE)
* Emily - Be your own hype squad (EN)
* Franka + Ellen - Join our study group! (EN/DE)

## Discussion

Discussion of names and suggestions will happen over in slack #speakers or in #clojurebridge-orga. We want to avoid posting names here publically **until they are confirmed**. 

@dantoml has volunteered to kick this off :rocket: with support from rest of team!

**Comment by lislis** [comment]
I briefly talked to [Joy Clark](https://twitter.com/iamjoyclark) at EuroClojure. She's interested in helping coaching at workshop and also giving a talk (which is the relevant part for this ticket). She's located in Düsseldorf, so we need to consider travel costs

**Comment by lislis** [comment]
Joy is out

**Comment by lislis** [comment]
Confirmend speakers:

Camilla - 3 annoying things about programming
Igor - The power of 2
Marie - Mitmischen
Emily - Be your own hype squad
Franka + Ellen - Join our study group!

**Comment by endocrimes** [comment]
Catherine - (Invited by @daiyi) just emailed me with her slides, about Switching to Tech from Academia

**Comment by lislis** [comment]
@DanToml sweet! She didn't fill out the form, but I guess the talk is in English?

**Comment by vsmart** [comment]
@DanToml 🎉 Yay more cool speakers \o/ 
Would be great if you could still get her to fill out the speaker form, esp since it includes agreement to CoC.

**Comment by endocrimes** [comment]
@vsmart / @lislis That is my guess - the slides had very little text. I'll email a link to that when I get to the study group later.

**Comment by vsmart** [comment]
@DanToml @daiyi @lislis @daveliepmann thanks y'all for assembling a diverse list of speakers.
