### ISSUE TITLE
Childcare

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#167]
We would like to offer child care again. Here is the issue from last time: https://github.com/clojurebridge-berlin/organization/issues/122

Unfortunately our old provider goodhands.eu closed down: https://www.familyhelden.de/goodbye-goodhands/

## Todo 

* [x] find a new agency or provider : http://kidsevent.com
* [x] contact agency for their general availability on workshop day, 9am-6pm
* [x] Once sign ups close, email people and ask for confirmation of their child care needs. How old is the child? We have a template for this.

**Comment by ellenkoenig** [comment]
She had a bunch of questions, but they seem to be generally available. She will contact you (@vsmart) with her questions via mail.

**Comment by vsmart** [comment]
We have an offer from http://www.proki-events.de/ for ~ 800 EUR. 

It's a bit pricy but I haven't found any other available agencies. If we end up needing child care, I guess we can go with them.

**Comment by vsmart** [comment]
Addition; If someone finds or knows of a cheaper option, do ping here!

**Comment by vsmart** [comment]
Good news, I asked around on twittter and found another agency that's much cheaper, http://www.agentur-puenktchen.de/de/ 

I told them by **23 September ** we will confirm yes/no whether we use their services and ** 30 September ** we tell them exact number/age of kids.

**Comment by vsmart** [comment]
We got an offer from them for 416 EUR. I'm going to accept it. 
We have at least 2 attendees who confirmed they would use our childcare services.

**Comment by vsmart** [comment]
I contacted the parents again to ask about allergies, etc, and to tell them that the childcare is confirmed. :white_check_mark:

**Comment by vsmart** [comment]
Childcare was provided by Agentur Puenktchen http://www.agentur-puenktchen.de/de/ :two_women_holding_hands: 
-- really looking forward to reading the  attendee feedback and y'alls thought on how this went at the retro. 
Tracking payment in #176 .
