### ISSUE TITLE
Checklist [On-The-Day] 

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#82]
I think it would be useful to have a checklist we can go through on the day to make sure we don't forget anything. 

Will use this issue as a draft. 
### Coaches training
- [x] whiteboard and markers 
- [x] pick up extra keycards
### some time before the workshop
- [x] get the key to the fuse box 
- [x] get the hausmeister's number 
- [ ] get some spare key cards 
- [ ] extra verlaengerungskabel + chargers?
### Morning of Workshop
- [ ] Set out breakfast 
- [ ] turn on coffee machine 
- [x] print check-in lists for coaches/attendees
- [ ] prepare a name tag table
- [ ] have someone standing downstairs & upstairs 
- [ ] check people in (on a list)
- [x] sign for quiet room saying `Quiet room | Ruhe Raum`
- [x] sign for toilets incl. all gender bathroom sign
### Jobs

Moved to https://docs.google.com/spreadsheets/d/1NqQPMjuEyXB0sqELGk0Dv54atP8tmih0rvqoyRIgvB0/edit#gid=0

**Comment by vsmart** [comment]
I've moved this to a wiki page -> https://github.com/clojurebridge-berlin/organization/wiki/Checklist:-Jobs-on-the-Day-✅
